/**
 * ENTropy API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserResponseDto } from './userResponseDto';
import { ScheduleResponseDto } from './scheduleResponseDto';


export interface AttendanceResponseDto { 
    id: number;
    schedule_id: number;
    student_id: number;
    status: string;
    note: string | null;
    created_at: string;
    updated_at: string;
    user: UserResponseDto;
    schedule: ScheduleResponseDto;
}

