/**
 * ENTropy API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AttendanceResponseDto { 
    id: number;
    schedule_id: number;
    student_id: number;
    status: string;
    note: string;
    created_at: string;
    updated_at: string;
}

