/**
 * ENTropy API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CampusResponseDto { 
    id: number;
    name: string;
    address: string;
    city: string;
    zip_code: string;
    region: string;
    director: string;
    phone: string;
    email: string;
    student_capacity: number;
    opening_date: string;
    status: string;
    created_at: string;
    updated_at: string;
}

