/**
 * ENTropy API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CourseResponseDto { 
    id: number;
    name: string;
    code: string;
    program_id: number;
    semester: number;
    credits: number;
    total_hours: number;
    instructor_id: number;
    room_id: number;
    status: string;
    created_at: string;
    updated_at: string;
}

