/**
 * ENTropy API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateRoomRequestDto { 
    /**
     * The name of the room
     */
    name: string;
    /**
     * The ID of the campus
     */
    campus_id: number;
    /**
     * The ID of the building
     */
    building_id: number;
    /**
     * The floor number
     */
    floor: number;
    /**
     * The seating capacity of the room
     */
    capacity: number;
    /**
     * The ID of the room type
     */
    room_type_id: number;
    /**
     * Equipment available in the room
     */
    equipement: string;
    /**
     * The status of the room
     */
    status: CreateRoomRequestDto.StatusEnum;
}
export namespace CreateRoomRequestDto {
    export const StatusEnum = {
        Booked: 'Booked',
        Available: 'Available',
        Unavailable: 'Unavailable'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


