/**
 * ENTropy API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreatePaymentDto { 
    /**
     * The ID of the student
     */
    student_id: number;
    /**
     * The invoice date
     */
    invoice_date: string;
    /**
     * The due date for payment
     */
    due_date: string;
    /**
     * The payment amount
     */
    amount: number;
    /**
     * The payment status
     */
    status: CreatePaymentDto.StatusEnum;
    /**
     * The actual payment date
     */
    payment_date: string | null;
    /**
     * The ID of the payment method
     */
    payment_method_id: number;
    /**
     * The academic year
     */
    academic_year: number;
    /**
     * The semester
     */
    semester: number;
    /**
     * Additional notes about the payment
     */
    notes: string;
}
export namespace CreatePaymentDto {
    export const StatusEnum = {
        NUMBER_0: 0,
        NUMBER_1: 1,
        NUMBER_2: 2
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


