/**
 * ENTropy API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateStudentDto { 
    /**
     * The first name of the user
     */
    first_name: string;
    /**
     * The last name of the user
     */
    last_name: string;
    /**
     * The email address of the user
     */
    email: string;
    /**
     * The password for the user\'s account
     */
    password: string;
    /**
     * The phone number of the user
     */
    phone: string;
    /**
     * The birthday of the user
     */
    birthday: string;
    /**
     * The ID of the campus the user is associated with
     */
    campus_id: number;
    /**
     * The ID of the program the student is enrolled in
     */
    program_id: number;
    /**
     * The year the student enrolled in the program
     */
    enrollment_year: number;
    /**
     * The current status of the student
     */
    status: CreateStudentDto.StatusEnum;
    /**
     * The address of the student
     */
    address: string;
    /**
     * The city where the student resides
     */
    city: string;
    /**
     * The zip code of the student\'s residence
     */
    zip_code: string;
    /**
     * The name of the student\'s emergency contact
     */
    emergency_contact: string;
    /**
     * The phone number of the student\'s emergency contact
     */
    emergency_phone: string;
}
export namespace CreateStudentDto {
    export const StatusEnum = {
        Active: 'Active',
        Inactive: 'Inactive'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


