/**
 * ENTropy API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateCourseDto { 
    /**
     * The name of the course
     */
    name: string;
    /**
     * The course code
     */
    code: string;
    /**
     * The ID of the program
     */
    program_id: number;
    /**
     * The semester of the course
     */
    semester: number;
    /**
     * The number of credits
     */
    credits: number;
    /**
     * Total hours for the course
     */
    total_hours: number;
    /**
     * The ID of the instructor
     */
    instructor_id: number;
    /**
     * The ID of the room
     */
    room_id: number;
    /**
     * The status of the course
     */
    status: CreateCourseDto.StatusEnum;
}
export namespace CreateCourseDto {
    export const StatusEnum = {
        Active: 'Active',
        Inactive: 'Inactive'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


