/**
 * ENTropy API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateAttendanceRequestDto { 
    /**
     * The ID of the schedule
     */
    schedule_id: number;
    /**
     * The ID of the student
     */
    student_id: number;
    /**
     * The attendance status
     */
    status: CreateAttendanceRequestDto.StatusEnum;
    /**
     * Optional note about attendance
     */
    note: string | null;
}
export namespace CreateAttendanceRequestDto {
    export const StatusEnum = {
        Present: 'PRESENT',
        Absent: 'ABSENT',
        Late: 'LATE',
        Excused: 'EXCUSED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


