/**
 * ENTropy API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateGradeRequestDto { 
    /**
     * The ID of the enrollment
     */
    enrollment_id: number;
    /**
     * The grade value
     */
    grade: number;
    /**
     * The name of the grade
     */
    name: string;
}

