/**
 * ENTropy API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateNotificationDto { 
    /**
     * The id of the user to notify
     */
    user_id: number;
    /**
     * The title of the notification
     */
    title: string;
    /**
     * The message of the notification
     */
    message: string;
}

