/**
 * ENTropy API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CourseResponseDto } from './courseResponseDto';
import { StudentResponseDto } from './studentResponseDto';


export interface EnrollmentResponseDto { 
    id: number;
    student_id: number;
    course_id: number;
    semester: number;
    academic_year: number;
    status: string;
    enrollment_date: string;
    created_at: string;
    updated_at: string;
    course: CourseResponseDto;
    student: StudentResponseDto;
}

