/**
 * ENTropy API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetNotificationResponseDto { 
    _id: number;
    user_id: number;
    title: string;
    message: string;
    target_url?: string;
    read_at?: string;
    createdAt: string;
    updatedAt: string;
    _v: number;
}

