/**
 * ENTropy API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnrollmentResponseDto } from './enrollmentResponseDto';


export interface GradeResponseDto { 
    id: number;
    enrollment_id: number;
    grade: number | null;
    name: string;
    enrollment: EnrollmentResponseDto;
}

