/**
 * ENTropy API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InstructorResponseDto } from './instructorResponseDto';


export interface InstructorListResponseDto { 
    total: number;
    page: number;
    limit: number;
    items: Array<InstructorResponseDto>;
}

