/**
 * ENTropy API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserResponseDto } from './userResponseDto';
import { SpecializationResponseDto } from './specializationResponseDto';
import { DepartmentResponseDto } from './departmentResponseDto';


export interface InstructorResponseDto { 
    department: DepartmentResponseDto;
    specialization: SpecializationResponseDto;
    user: UserResponseDto;
    user_id: number;
    department_id: number;
    status: string;
    hire_date: string;
    specialization_id: number;
}

