/**
 * ENTropy API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaymentMethodResponseDto } from './paymentMethodResponseDto';


export interface PaymentMethodListResponseDto { 
    total: number;
    page: number;
    limit: number;
    items: Array<PaymentMethodResponseDto>;
}

