/**
 * ENTropy API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PaymentResponseDto { 
    id: number;
    student_id: number;
    invoice_date: string;
    due_date: string;
    amount: number;
    status: number;
    payment_date: object | null;
    payment_method_id: number;
    academic_year: number;
    semester: number;
    notes: string;
    created_at: string;
    updated_at: string;
}

