/**
 * ENTropy API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProgramResponseDto { 
    id: number;
    name: string;
    program_type_id: number;
    duration_in_years: number;
    annual_tuition_fee: number;
    department: string;
    coordinator: string;
    max_students: number;
    status: string;
    created_at: string;
    updated_at: string;
}

