/**
 * ENTropy API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RefreshTokenDto { 
    /**
     * Refresh token given by the backend addressed to the refresh endpoint
     */
    refresh_token: string;
}

