/**
 * ENTropy API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RoomResponseDto { 
    id: number;
    name: string;
    campus_id: number;
    building_id: number;
    floor: number;
    capacity: number;
    room_type_id: number;
    equipement: string;
    status: string;
    created_at: string;
    updated_at: string;
}

