/**
 * ENTropy API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoomResponseDto } from './roomResponseDto';


export interface RoomListResponseDto { 
    total: number;
    page: number;
    limit: number;
    items: Array<RoomResponseDto>;
}

