/**
 * ENTropy API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CourseResponseDto } from './courseResponseDto';


export interface ScheduleResponseDto { 
    id: number;
    event_id: number;
    course_id: number;
    instructor_id: number;
    room_id: number;
    start_date: string;
    end_date: string;
    semester: number;
    academic_year: number;
    status: number;
    last_modified: string;
    created_at: string;
    updated_at: string;
    course: CourseResponseDto;
}

