/**
 * ENTropy API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserResponseDto } from './userResponseDto';
import { ProgramResponseDto } from './programResponseDto';


export interface StudentResponseDto { 
    program: ProgramResponseDto;
    user: UserResponseDto;
    user_id: number;
    program_id: number;
    enrollment_year: number;
    status: string;
    address: string;
    city: string;
    zip_code: string;
    emergency_contact: string;
    emergency_phone: string;
}

