/**
 * ENTropy API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TokenResponseDto { 
    /**
     * Access token given by the backend
     */
    access_token: string;
    /**
     * Refresh token given by the backend
     */
    refresh_token: string;
    /**
     * The user ID
     */
    user_id: number;
    /**
     * The user email
     */
    email: string;
}

