/**
 * ENTropy API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateBuildingDto { 
    /**
     * The name of the building
     */
    name?: string;
    /**
     * The ID of the campus
     */
    campus_id?: number;
}

