/**
 * ENTropy API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateEnrollmentDto { 
    /**
     * The ID of the student
     */
    student_id?: number;
    /**
     * The ID of the course
     */
    course_id?: number;
    /**
     * The semester
     */
    semester?: number;
    /**
     * The academic year
     */
    academic_year?: number;
    /**
     * The enrollment status
     */
    status?: UpdateEnrollmentDto.StatusEnum;
    /**
     * The enrollment date
     */
    enrollment_date?: string;
}
export namespace UpdateEnrollmentDto {
    export const StatusEnum = {
        InProgress: 'In progress',
        Validated: 'Validated'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


