/**
 * ENTropy API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateScheduleDto { 
    /**
     * The ID of the course
     */
    course_id?: number;
    /**
     * The ID of the instructor
     */
    instructor_id?: number;
    /**
     * The ID of the room
     */
    room_id?: number;
    /**
     * The start date and time
     */
    start_date?: string;
    /**
     * The end date and time
     */
    end_date?: string;
    /**
     * The semester
     */
    semester?: number;
    /**
     * The academic year
     */
    academic_year?: number;
    /**
     * The schedule status
     */
    status?: UpdateScheduleDto.StatusEnum;
}
export namespace UpdateScheduleDto {
    export const StatusEnum = {
        NUMBER_1: 1,
        NUMBER_2: 2,
        NUMBER_3: 3
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


