/**
 * ENTropy API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateAttendanceDto { 
    /**
     * The ID of the schedule
     */
    schedule_id?: number;
    /**
     * The ID of the student
     */
    student_id?: number;
    /**
     * The attendance status
     */
    status?: UpdateAttendanceDto.StatusEnum;
    /**
     * Optional note about attendance
     */
    note?: object | null;
}
export namespace UpdateAttendanceDto {
    export const StatusEnum = {
        Present: 'PRESENT',
        Absent: 'ABSENT',
        Late: 'LATE',
        Excused: 'EXCUSED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


