/**
 * ENTropy API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateCampusDto { 
    /**
     * The name of the campus
     */
    name?: string;
    /**
     * The street address of the campus
     */
    address?: string;
    /**
     * The city where the campus is located
     */
    city?: string;
    /**
     * The postal code
     */
    zip_code?: string;
    /**
     * The region of the campus
     */
    region?: string;
    /**
     * The name of the campus director
     */
    director?: string;
    /**
     * The phone number of the campus
     */
    phone?: string;
    /**
     * The email address of the campus
     */
    email?: string;
    /**
     * The maximum student capacity
     */
    student_capacity?: number;
    /**
     * The opening date of the campus
     */
    opening_date?: string;
    /**
     * The status of the campus
     */
    status?: UpdateCampusDto.StatusEnum;
}
export namespace UpdateCampusDto {
    export const StatusEnum = {
        Active: 'Active',
        Inactive: 'Inactive'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


