/**
 * ENTropy API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserResponseDto } from './userResponseDto';


export interface UserListResponseDto { 
    total: number;
    page: number;
    limit: number;
    items: Array<UserResponseDto>;
}

