export * from './attendance.service';
import { AttendanceService } from './attendance.service';
export * from './authentication.service';
import { AuthenticationService } from './authentication.service';
export * from './authorization.service';
import { AuthorizationService } from './authorization.service';
export * from './building.service';
import { BuildingService } from './building.service';
export * from './campus.service';
import { CampusService } from './campus.service';
export * from './course.service';
import { CourseService } from './course.service';
export * from './enrollment.service';
import { EnrollmentService } from './enrollment.service';
export * from './grade.service';
import { GradeService } from './grade.service';
export * from './instructor.service';
import { InstructorService } from './instructor.service';
export * from './notifications.service';
import { NotificationsService } from './notifications.service';
export * from './payment.service';
import { PaymentService } from './payment.service';
export * from './paymentMethod.service';
import { PaymentMethodService } from './paymentMethod.service';
export * from './room.service';
import { RoomService } from './room.service';
export * from './roomType.service';
import { RoomTypeService } from './roomType.service';
export * from './schedule.service';
import { ScheduleService } from './schedule.service';
export * from './student.service';
import { StudentService } from './student.service';
export * from './user.service';
import { UserService } from './user.service';
export * from './userRole.service';
import { UserRoleService } from './userRole.service';
export const APIS = [AttendanceService, AuthenticationService, AuthorizationService, BuildingService, CampusService, CourseService, EnrollmentService, GradeService, InstructorService, NotificationsService, PaymentService, PaymentMethodService, RoomService, RoomTypeService, ScheduleService, StudentService, UserService, UserRoleService];
